###
# This is the place to override the rainbows cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "rainbows/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Rainbows timout:
#
#normal[:rainbows][:timeout] = 30
